# This is a basic workflow to help you get started with Actions

name: Create PHPdoc

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'main'
      - 'fix-002'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete phpdoc branch
        run: |
          branch_is_existing=$(
            git fetch origin phpdoc &&
            echo true ||
            echo false
          )
          if: ${branch_is_existing} == 'true'
            git push --delete origin phpdoc

      - name: Create new branch for push phpdoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "phpdoc"
          git push origin "phpdoc"

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d ./src -t ./docs

      - name: Add change log to Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add docs/
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push origin "phpdoc"      
      
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -b main -m "Update phpdoc"
